import { SignInButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Head from "next/head";
import CreatePostWizard from "~/components/create-post-wizard";
import Feed from "~/components/feed";
import { api } from "~/utils/api";

dayjs.extend(relativeTime);

function Home() {
  const { isLoaded: isUserLoading, isSignedIn } = useUser();

  // Start fetching the post earlier asap
  api.posts.getAll.useQuery();

  // Render and empty div if both aren't loaded, just to reduce the user load time
  if (!isUserLoading) return <div />;

  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="description" content="Generated by create-t3-app" />
        <title>Create T3 App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-200 md:max-w-2xl">
          <div className="flex border-b border-slate-200 p-4">
            <div className="flex w-full justify-center">
              {!isSignedIn ? <SignInButton /> : <CreatePostWizard />}
            </div>
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
}

export default Home;
